### ISSUE TITLE
my system is archlinux,building mpv to get some error. 

### ISSUE THREAD

**Issue by skyseedtbgmailcom** [JeffyCN/mpv#1]
[ 47/236] Compiling demux/demux_mkv.c
../audio/out/ao_pulse.c:556:13: error: conflicting types for 'pause'; have 'void(struct ao *)'
  556 | static void pause(struct ao *ao)
      |             ^~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/sys/param.h:28,
                 from /usr/include/pulse/sample.h:26,
                 from /usr/include/pulse/def.h:28,
                 from /usr/include/pulse/direction.h:23,
                 from /usr/include/pulse/pulseaudio.h:24,
                 from ../audio/out/ao_pulse.c:29:
/usr/include/unistd.h:489:12: note: previous declaration of 'pause' with type 'int(void)'
  489 | extern int pause (void);
      |            ^~~~~

../audio/filter/af_lavcac3enc.c: In function 'reinit':
../audio/filter/af_lavcac3enc.c:106:5: warning: 'channels' is deprecated [-Wdeprecated-declarations]
  106 |     s->lavc_actx->channels = chmap.num;
      |     ^
In file included from ../audio/filter/af_lavcac3enc.c:28:
/usr/include/libavcodec/avcodec.h:1006:9: note: declared here
 1006 |     int channels;
      |         ^~~~~~~~
../audio/filter/af_lavcac3enc.c:107:5: warning: 'channel_layout' is deprecated [-Wdeprecated-declarations]
  107 |     s->lavc_actx->channel_layout = mp_chmap_to_lavc(&chmap);
      |     ^
/usr/include/libavcodec/avcodec.h:1060:14: note: declared here
 1060 |     uint64_t channel_layout;
      |              ^~~~~~~~~~~~~~
../audio/filter/af_lavcac3enc.c: In function 'process':
../audio/filter/af_lavcac3enc.c:156:5: warning: 'av_init_packet' is deprecated [-Wdeprecated-declarations]
  156 |     av_init_packet(&pkt);
      |     ^~~~~~~~~~~~~~
In file included from /usr/include/libavcodec/avcodec.h:45:
/usr/include/libavcodec/packet.h:512:6: note: declared here
  512 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
../audio/filter/af_lavcac3enc.c: In function 'af_lavcac3enc_create':
../audio/filter/af_lavcac3enc.c:286:20: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  286 |     s->lavc_acodec = avcodec_find_encoder_by_name(s->opts->encoder);
      |                    ^
../audio/filter/af_lavcac3enc.c:305:9: warning: 'channel_layouts' is deprecated [-Wdeprecated-declarations]
  305 |         !s->lavc_acodec->channel_layouts)
      |         ^
In file included from /usr/include/libavcodec/avcodec.h:40:
/usr/include/libavcodec/codec.h:226:21: note: declared here
  226 |     const uint64_t *channel_layouts;         ///< array of support channel layouts, or NULL if unknown. array is terminated by 0
      |                     ^~~~~~~~~~~~~~~
../audio/filter/af_lavcac3enc.c:337:5: warning: 'channel_layouts' is deprecated [-Wdeprecated-declarations]
  337 |     const uint64_t *lch = s->lavc_acodec->channel_layouts;
      |     ^~~~~
/usr/include/libavcodec/codec.h:226:21: note: declared here
  226 |     const uint64_t *channel_layouts;         ///< array of support channel layouts, or NULL if unknown. array is terminated by 0
      |                     ^~~~~~~~~~~~~~~

Waf: Leaving directory `/tmp/mpv/build'
Build failed

**Comment by JeffyCN** [comment]
this error doesn't related to my patches, please try official mpv.

if it has the same issue, please report to mpv upstream
if it works, then you can try to port my patches from the closest branch

**Comment by JeffyCN** [comment]
one possible workaround would be:
```
+++ b/audio/out/ao_pulse.c
@@ -553,7 +553,7 @@ static void reset(struct ao *ao)
 }

 // Pause the audio stream by corking it on the server
-static void pause(struct ao *ao)
+static void _pause(struct ao *ao)
 {
     cork(ao, true);
 }
@@ -824,7 +824,7 @@ const struct ao_driver audio_out_pulse = {
     .get_space = get_space,
     .play      = play,
     .get_delay = get_delay,
-    .pause     = pause,
+    .pause     = _pause,
     .resume    = resume,
     .drain     = drain,
```

**Comment by skyseedtbgmailcom** [comment]
I had installed office mpv succefully,it can support vo=gpu,but not support vo=xv,So I want to install your version.Now the audio has be normal by your comment.Now get new issue.
[ 29/236] Compiling video/out/gpu/osd.c
In file included from ../video/out/placebo/utils.c:2:
../video/out/placebo/utils.h:8:30: warning: 'struct pl_context' declared inside parameter list will not be visible outside of this definition or declaration
    8 | void mppl_ctx_set_log(struct pl_context *ctx, struct mp_log *log, bool probing);
      |                              ^~~~~~~~~~
../video/out/placebo/utils.c:4:36: error: 'PL_LOG_ALL' undeclared here (not in a function)
    4 | static const int pl_log_to_msg_lev[PL_LOG_ALL+1] = {
      |                                    ^~~~~~~~~~
../video/out/placebo/utils.c:5:6: error: 'PL_LOG_FATAL' undeclared here (not in a function)
    5 |     [PL_LOG_FATAL] = MSGL_FATAL,
      |      ^~~~~~~~~~~~
../video/out/placebo/utils.c:6:6: error: 'PL_LOG_ERR' undeclared here (not in a function)
    6 |     [PL_LOG_ERR]   = MSGL_ERR,
      |      ^~~~~~~~~~
../video/out/placebo/utils.c:7:6: error: 'PL_LOG_WARN' undeclared here (not in a function)
    7 |     [PL_LOG_WARN]  = MSGL_WARN,
      |      ^~~~~~~~~~~
../video/out/placebo/utils.c:8:6: error: 'PL_LOG_INFO' undeclared here (not in a function)
    8 |     [PL_LOG_INFO]  = MSGL_V,
      |      ^~~~~~~~~~~
../video/out/placebo/utils.c:9:6: error: 'PL_LOG_DEBUG' undeclared here (not in a function)
    9 |     [PL_LOG_DEBUG] = MSGL_DEBUG,
      |      ^~~~~~~~~~~~
../video/out/placebo/utils.c:10:6: error: 'PL_LOG_TRACE' undeclared here (not in a function)
   10 |     [PL_LOG_TRACE] = MSGL_TRACE,
      |      ^~~~~~~~~~~~
../video/out/placebo/utils.c:13:32: error: array type has incomplete element type 'enum pl_log_level'
   13 | static const enum pl_log_level msg_lev_to_pl_log[MSGL_MAX+1] = {
      |                                ^~~~~~~~~~~~~~~~~
../video/out/placebo/utils.c:26:62: error: parameter 1 ('level') has incomplete type
   26 | static const enum pl_log_level probing_map(enum pl_log_level level)
      |                                            ~~~~~~~~~~~~~~~~~~^~~~~
../video/out/placebo/utils.c:26:32: error: return type is an incomplete type
   26 | static const enum pl_log_level probing_map(enum pl_log_level level)
      |                                ^~~~~~~~~~~
../video/out/placebo/utils.c:26:32: warning: function declaration isn't a prototype [-Wstrict-prototypes]
../video/out/placebo/utils.c: In function 'probing_map':
../video/out/placebo/utils.c:30:16: warning: 'return' with a value, in function returning void [-Wreturn-type]
   30 |         return PL_LOG_ERR;
      |                ^~~~~~~~~~
../video/out/placebo/utils.c:26:32: note: declared here
   26 | static const enum pl_log_level probing_map(enum pl_log_level level)
      |                                ^~~~~~~~~~~
../video/out/placebo/utils.c:34:16: warning: 'return' with a value, in function returning void [-Wreturn-type]
   34 |         return PL_LOG_INFO;
      |                ^~~~~~~~~~~
../video/out/placebo/utils.c:26:32: note: declared here
   26 | static const enum pl_log_level probing_map(enum pl_log_level level)
      |                                ^~~~~~~~~~~
../video/out/placebo/utils.c:37:16: warning: 'return' with a value, in function returning void [-Wreturn-type]
   37 |         return level;
      |                ^~~~~
../video/out/placebo/utils.c:26:32: note: declared here
   26 | static const enum pl_log_level probing_map(enum pl_log_level level)
      |                                ^~~~~~~~~~~
../video/out/placebo/utils.c: At top level:
../video/out/placebo/utils.c:41:50: error: parameter 2 ('level') has incomplete type
   41 | static void log_cb(void *priv, enum pl_log_level level, const char *msg)
      |                                ~~~~~~~~~~~~~~~~~~^~~~~
../video/out/placebo/utils.c:41:13: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   41 | static void log_cb(void *priv, enum pl_log_level level, const char *msg)
      |             ^~~~~~
../video/out/placebo/utils.c:47:58: error: parameter 2 ('level') has incomplete type
   47 | static void log_cb_probing(void *priv, enum pl_log_level level, const char *msg)
      |                                        ~~~~~~~~~~~~~~~~~~^~~~~
../video/out/placebo/utils.c:47:13: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   47 | static void log_cb_probing(void *priv, enum pl_log_level level, const char *msg)
      |             ^~~~~~~~~~~~~~
../video/out/placebo/utils.c:53:30: warning: 'struct pl_context' declared inside parameter list will not be visible outside of this definition or declaration
   53 | void mppl_ctx_set_log(struct pl_context *ctx, struct mp_log *log, bool probing)
      |                              ^~~~~~~~~~
../video/out/placebo/utils.c:53:6: error: conflicting types for 'mppl_ctx_set_log'; have 'void(struct pl_context *, struct mp_log *, _Bool)'
   53 | void mppl_ctx_set_log(struct pl_context *ctx, struct mp_log *log, bool probing)
      |      ^~~~~~~~~~~~~~~~
../video/out/placebo/utils.h:8:6: note: previous declaration of 'mppl_ctx_set_log' with type 'void(struct pl_context *, struct mp_log *, _Bool)'
    8 | void mppl_ctx_set_log(struct pl_context *ctx, struct mp_log *log, bool probing);
      |      ^~~~~~~~~~~~~~~~
../video/out/placebo/utils.c: In function 'mppl_ctx_set_log':
../video/out/placebo/utils.c:57:5: error: implicit declaration of function 'pl_context_update' [-Werror=implicit-function-declaration]
   57 |     pl_context_update(ctx, &(struct pl_context_params) {
      |     ^~~~~~~~~~~~~~~~~
../video/out/placebo/utils.c:58:10: error: 'struct pl_context_params' has no member named 'log_cb'
   58 |         .log_cb      = probing ? log_cb_probing : log_cb,
      |          ^~~~~~
../video/out/placebo/utils.c:58:24: warning: excess elements in struct initializer
   58 |         .log_cb      = probing ? log_cb_probing : log_cb,
      |                        ^~~~~~~
../video/out/placebo/utils.c:58:24: note: (near initialization for '(anonymous)')
../video/out/placebo/utils.c:59:10: error: 'struct pl_context_params' has no member named 'log_level'
   59 |         .log_level   = msg_lev_to_pl_log[mp_msg_level(log)],
      |          ^~~~~~~~~
../video/out/placebo/utils.c:59:24: warning: excess elements in struct initializer
   59 |         .log_level   = msg_lev_to_pl_log[mp_msg_level(log)],
      |                        ^~~~~~~~~~~~~~~~~
../video/out/placebo/utils.c:59:24: note: (near initialization for '(anonymous)')
../video/out/placebo/utils.c:60:10: error: 'struct pl_context_params' has no member named 'log_priv'
   60 |         .log_priv    = log,
      |          ^~~~~~~~
../video/out/placebo/utils.c:60:24: warning: excess elements in struct initializer
   60 |         .log_priv    = log,
      |                        ^~~
../video/out/placebo/utils.c:60:24: note: (near initialization for '(anonymous)')
../video/out/placebo/utils.c:57:56: error: invalid use of undefined type 'struct pl_context_params'
   57 |     pl_context_update(ctx, &(struct pl_context_params) {
      |                                                        ^
../video/out/placebo/utils.c: At top level:
../video/out/placebo/utils.c:13:32: warning: 'msg_lev_to_pl_log' defined but not used [-Wunused-variable]
   13 | static const enum pl_log_level msg_lev_to_pl_log[MSGL_MAX+1] = {
      |                                ^~~~~~~~~~~~~~~~~
../video/out/placebo/utils.c:4:18: warning: 'pl_log_to_msg_lev' defined but not used [-Wunused-variable]
    4 | static const int pl_log_to_msg_lev[PL_LOG_ALL+1] = {
      |                  ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

[ 30/236] Compiling video/out/gpu/libmpv_gpu.c
../audio/decode/ad_spdif.c: In function 'determine_codec_params':
../audio/decode/ad_spdif.c:119:22: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  119 |     AVCodec *codec = avcodec_find_decoder(spdif_ctx->codec_id);
      |                      ^~~~~~~~~~~~~~~~~~~~

Waf: Leaving directory `/tmp/mpv/build'
Build failed

**Comment by skyseedtbgmailcom** [comment]
If I want to install offical mpv to support vo=xv,which pathes should I port.My device soc is rk3588s.

**Comment by JeffyCN** [comment]
by official mpv, i mean build-from-source.

it's offcial mpv issue(could be version mismatch), my patches are impossible to cause those build issues

**Comment by JeffyCN** [comment]
or you can try to find the installed mpv's source code, and apply my patches of the closest branch

**Comment by JeffyCN** [comment]
and if you want to use rk's custom xv, you may need to use the custom xserver as well

**Comment by skyseedtbgmailcom** [comment]
I know you saying about official build-from-source.I had installed it before successfully.But I don't know how to apply your patches of the closet branch,can you provide specific details,thanks.

**Comment by JeffyCN** [comment]
just find the closest branch in this repo(it has branches from 0.27 ~ 0.32), use git cherry-pick to pick patches to your source code.

**Comment by JeffyCN** [comment]
for example 0.27:
https://github.com/JeffyCN/mpv/commits/ubuntu/0.27.2-1ubuntu1

you need xv, so pick my vo_xv patches(3 patches)

**Comment by skyseedtbgmailcom** [comment]
> and if you want to use rk's custom xv, you may need to use the custom xserver as well

Following your suggestion now I have solved the problem of mpv playing with xv. As you said I also need to custom xserver, because mpv only shows a green screen when playing video. What should I do next? Package support for xv to the official xorg-server.

**Comment by JeffyCN** [comment]
check:
https://github.com/JeffyCN/xorg-xserver/branches

choose a closest branch, and port glamor related patches from it, from base version to "glamor: xv: Fix invalid accessing of plane attributes for NV12"
